# Generated by Django 3.0 on 2020-04-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscore',
            name='std_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='examscore',
            name='subject',
            field=models.CharField(choices=[('math', 'คณิตศาสตร์'), ('sci', 'วิทยาศาสตร์'), ('art', 'ศิลปะ'), ('eng', 'อังกฤษ')], default='math', max_length=200),
        ),
    ]
