# Generated by Django 3.0 on 2020-04-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200411_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examscore',
            old_name='std_name',
            new_name='stdname',
        ),
    ]
